"""Authoritative category guidance returned by /api/v1/operators/categories.

Each entry provides the agent with:
- ``use_for``  : the data-engineering jobs this category is genuinely intended for
- ``not_for``  : common mis-mappings observed in agent traces (anti-patterns)
- ``examples`` : 3-5 representative operator names so the agent has anchors when
                 it issues the follow-up ``list_operators?category=...`` call

The dictionary keys MUST stay in sync with the ``type.level_1`` values of the
operator registry. The endpoint cross-checks against the live registry and
backfills any unknown category with a stub so we never crash if a new category
is introduced upstream.
"""

CATEGORY_GUIDE: dict[str, dict] = {
    "core_text": {
        "use_for": (
            "AI4S 科学文本默认入口：论文/摘要/章节的结构化抽取、claim-evidence 绑定、"
            "有依据的 QA/摘要，以及跨 source/output 字段的事实与数值一致性评估；"
            "也用于通用文本→QA / 多跳 QA / 长文本切块生成和 prompt-driven 的 "
            "filter / refine / evaluator (PromptedFilter/PromptedRefiner/"
            "PromptedEvaluator)；表格/字段重写用 PandasOperator。"
            "首选这一类做『从原始文本生成 SFT 训练数据』。"
        ),
        "not_for": (
            "**不要**用 SFTGeneratorSeed —— 那个属于 text_sft，是从已有 SFT "
            "种子扩展，而不是从原始文本生成 QA。需要『基础 QA 生成』时直接选 "
            "Text2QAGenerator 或 Text2MultiHopQAGenerator。"
            "也不要用它做 PT 语料质量过滤（去 text_pt）或代码相关任务（去 code）。"
        ),
        "examples": [
            "Text2QAGenerator", "Text2MultiHopQAGenerator",
            "ChunkedPromptedGenerator", "PromptedFilter",
            "PromptedRefiner", "PandasOperator",
        ],
    },
    "general_text": {
        "use_for": (
            "纯文本表面层清洗与统计：基于规则的 Filter（长度、字符比例、"
            "html 实体、URL、PII），N-gram / Hash 去重，BLEU/CIDEr 等无 LLM "
            "评测。**所有不需要 LLM 调用的『通用文本质量过滤』都来这里找**。"
        ),
        "not_for": (
            "需要语义理解的过滤（如『基于 LLM 判断是否为优质问题』）应该用 "
            "core_text 的 PromptedFilter；代码质量过滤去 code；"
            "PT 语料 perplexity/edu-classifier 过滤去 text_pt。"
        ),
        "examples": [
            "CharNumberFilter", "NgramFilter", "HashDeduplicateFilter",
            "HtmlEntityRefiner", "LLMLanguageFilter",
            "ContentNullFilter", "BleuSampleEvaluator",
        ],
    },
    "text_sft": {
        "use_for": (
            "已经有 SFT 数据（instruction / response 列）后做的事："
            "用 Condor / Treeinstruct / Deita / Alpagasus / Superfiltering / "
            "RM / Instag 等方法对 SFT 样本打分、过滤、扩写。"
        ),
        "not_for": (
            "**不要**在『还没生成 QA / instruction』的阶段用这一类。"
            "如果输入只是原始文档，应该先去 core_text（Text2QAGenerator）"
            "或 reasoning（ReasoningQuestionGenerator）生成训练样本，"
            "再回来走 text_sft 做质量评估。SFTGeneratorSeed 也不是『从文本生成 QA』，"
            "它需要既有 SFT 种子。"
        ),
        "examples": [
            "CondorGenerator", "CondorRefiner", "DeitaQualityFilter",
            "AlpagasusFilter", "SuperfilteringFilter", "TreeinstructFilter",
        ],
    },
    "text_pt": {
        "use_for": (
            "**预训练（PT）语料**质量过滤：perplexity 过滤、FineWeb-Edu 分类器、"
            "DebertaV3 质量、CCNet 去重。Phi4QAGenerator 是 PT 风格的 QA 合成。"
        ),
        "not_for": (
            "SFT/QA 数据评估走 text_sft；通用规则去重走 general_text；"
            "推理/数学数据去 reasoning。"
        ),
        "examples": [
            "PerplexityFilter", "FineWebEduFilter", "DebertaV3Filter",
            "CCNetDeduplicateFilter", "Phi4QAGenerator",
        ],
    },
    "reasoning": {
        "use_for": (
            "数学/逻辑推理 CoT 数据：从问题生成 CoT 答案、答案抽取、"
            "题目难度/分类评估、答案 N-gram/format/judge 过滤、"
            "PT 格式转换。**只有当任务明确是 math / step-by-step CoT 时才选这里**。"
        ),
        "not_for": (
            "通用 QA 生成不在这里，去 core_text；代码推理不在这里，去 code；"
            "纯文本清洗不在这里，去 general_text。"
        ),
        "examples": [
            "ReasoningQuestionGenerator", "ReasoningAnswerGenerator",
            "ReasoningQuestionFilter", "ReasoningAnswerFormatterFilter",
            "ReasoningQuestionDifficultySampleEvaluator",
        ],
    },
    "code": {
        "use_for": (
            "代码数据：从代码生成指令、从指令生成代码、代码质量打分、"
            "auto-generated 代码检测、长度/编码异常过滤、sandbox 评估。"
        ),
        "not_for": (
            "自然语言 QA / refine 不在这里；代码相关 SFT 评估也不能直接套通用 "
            "DeitaQuality（去 text_sft 但参数要切换 instruction/response）。"
        ),
        "examples": [
            "CodeInstructionGenerator", "CodeCodeToInstructionGenerator",
            "CodeQualityScoreFilter", "CodeAutoGeneratedFilter",
            "CodeSandboxSampleEvaluator",
        ],
    },
    "conversations": {
        "use_for": (
            "多轮对话/智能体场景的合成与评估：场景抽取/扩写、原子任务/"
            "顺序任务生成、function-calling 对话生成与评估、组合任务过滤。"
        ),
        "not_for": (
            "单轮 QA 不属于这里（去 core_text）；单条 instruction 评估不属于这里"
            "（去 text_sft）。"
        ),
        "examples": [
            "MultiTurnConversationGenerator", "ConsistentChatGenerator",
            "ScenarioExtractGenerator", "FunctionGenerator",
            "FuncCallConversationSampleEvaluator",
        ],
    },
    "knowledge_cleaning": {
        "use_for": (
            "**文档/URL 摄取链路**：File/URL→Markdown 转换（API/Flash/Local 三种），"
            "KBC 切块、清洗、批量 QA 生成。把『PDF/HTML/网页 → 训练数据』的"
            "前几步全部放在这里。科学论文 PDF 应先检查双栏阅读顺序、页眉页脚、"
            "表格/公式缺失和章节边界，再把干净文本交给 core_text。"
        ),
        "not_for": (
            "如果输入已经是干净纯文本，跳过这一类，直接去 core_text。"
            "API-only 部署中 KBCChunkGenerator 等可能因依赖缺失不可用，"
            "此时回退到 core_text 的 ChunkedPromptedGenerator。"
        ),
        "examples": [
            "FileOrURLToMarkdownConverterAPI", "FileOrURLToMarkdownConverterFlash",
            "KBCChunkGenerator", "KBCMultiHopQAGeneratorBatch",
            "MathBookQuestionExtract",
        ],
    },
    "agentic_rag": {
        "use_for": (
            "Agentic / 多跳 RAG 训练数据合成：原子任务、宽度/深度 QA 生成与 F1 评估。"
        ),
        "not_for": "普通单跳 QA 走 core_text；多轮对话走 conversations。",
        "examples": [
            "AgenticRAGAtomicTaskGenerator", "AgenticRAGDepthQAGenerator",
            "AgenticRAGWidthQAGenerator", "AgenticRAGQAF1SampleEvaluator",
        ],
    },
    "text2sql": {
        "use_for": "Text2SQL 数据生成与评估：可执行性过滤、组件分类、CoT 投票生成。",
        "not_for": "通用 QA / 推理任务不要走这里。",
        "examples": [
            "Text2SQLCoTVotingGenerator", "SQLExecutabilityFilter",
            "SQLExecutionFilter", "SQLComponentClassifier",
        ],
    },
    "pdf2vqa": {
        "use_for": "PDF→视觉问答数据：MinerU 输入构造、PDF/QA 合并、VQA 格式化、LLM 输出解析。",
        "not_for": "纯文本 QA 走 core_text；普通 OCR/markdown 走 knowledge_cleaning。",
        "examples": [
            "MinerU2LLMInputOperator", "PDF_Merger", "QA_Merger",
            "VQAFormatter", "LLMOutputParser",
        ],
    },
    "core_vision": {
        "use_for": "通用视觉 QA 合成（PromptedVQAGenerator）。",
        "not_for": "PDF 专用流水线去 pdf2vqa。",
        "examples": ["PromptedVQAGenerator"],
    },
    "core_speech": {
        "use_for": "语音转文本（Speech2TextGenerator）。",
        "not_for": "其他模态不属于这里。",
        "examples": ["Speech2TextGenerator"],
    },
    "chemistry": {
        "use_for": "化学结构专用能力：从文本抽取 SMILES、SMILES 等价数据集评估。",
        "not_for": (
            "不要因为论文主题是 chemistry/化学就选这里；论文摘要、方法、结果、"
            "claim-evidence 或 QA 仍走 core_text。只有明确需要 SMILES 操作时才选。"
        ),
        "examples": [
            "ExtractSmilesFromTextGenerator", "SmilesEquivalenceDatasetEvaluator",
        ],
    },
}


def build_category_response(op_list: list[dict]) -> dict[str, dict]:
    """Return ``{category: {count, use_for, not_for, examples}}``.

    Counts are recomputed from the live registry; use_for/not_for come from
    CATEGORY_GUIDE. Categories present in the registry but missing from the
    guide get an "unknown" stub so the response is never silently lossy.
    """
    counts: dict[str, int] = {}
    for op in op_list:
        cat = (op.get("type") or {}).get("level_1") or "unknown"
        counts[cat] = counts.get(cat, 0) + 1

    result: dict[str, dict] = {}
    for cat, n in counts.items():
        guide = CATEGORY_GUIDE.get(cat, {})
        result[cat] = {
            "count": n,
            "use_for": guide.get("use_for", "(no guidance available)"),
            "not_for": guide.get("not_for", "(no guidance available)"),
            "examples": guide.get("examples", []),
        }
    return result


def valid_categories(op_list: list[dict]) -> list[str]:
    """Categories actually present in the registry (sorted)."""
    seen = set()
    for op in op_list:
        cat = (op.get("type") or {}).get("level_1")
        if cat:
            seen.add(cat)
    return sorted(seen)


def recommend_categories(task_description: str, dataset_columns: list[str] | None = None, max_categories: int = 2) -> dict:
    """Heuristic MCP helper: recommend at most ``max_categories`` top-level categories.

    The goal is not perfect semantic routing. The goal is to stop the agent from
    spraying 5-10 category queries and blowing context. Recommendations are kept
    short, deterministic, and grounded in the same anti-patterns already encoded
    in ``CATEGORY_GUIDE``.
    """
    dataset_columns = dataset_columns or []
    task_lower = (task_description or '').lower()
    col_lower = [c.lower() for c in dataset_columns]

    score_map: dict[str, int] = {}
    reason_map: dict[str, list[str]] = {}
    avoid_map: dict[str, list[str]] = {}

    def add(cat: str, score: int, reason: str) -> None:
        score_map[cat] = score_map.get(cat, 0) + score
        reason_map.setdefault(cat, []).append(reason)

    def avoid(cat: str, reason: str) -> None:
        avoid_map.setdefault(cat, []).append(reason)

    def has_any(*keywords: str) -> bool:
        return any(k in task_lower for k in keywords)

    science_task = has_any(
        'scientific paper', 'research paper', 'paper abstract', 'manuscript',
        'literature', 'methods section', 'results section', 'experiment',
        'claim-evidence', 'claim evidence', 'evidence quote', 'citation',
        'scientific', '论文', '文献', '科研', '科学文本', '实验结果',
        '方法章节', '结果章节', '证据片段', '引用',
    )
    science_columns = any(
        col in {
            'abstract', 'paper_text', 'section_text', 'methods', 'results',
            'paper_id', 'document_id', 'doi', 'evidence', 'evidence_quote',
        }
        for col in col_lower
    )

    if science_task or science_columns:
        add(
            'core_text',
            8 if science_task else 4,
            'scientific text defaults to evidence-grounded core_text extraction, QA, or evaluation',
        )

    if has_any('multi-hop', 'multihop', 'qa pair', 'question-answer', 'question answer', '问答', '多跳', 'qa对', 'qa 对'):
        add('core_text', 8, 'task explicitly asks for QA / multi-hop QA generation')
        avoid('text_sft', 'QA-from-text is not a text_sft construction task')

    if has_any('summary', 'summarize', '摘要', '总结', 'classify', 'classification', 'sentiment', 'score', 'rewrite', 'paraphrase'):
        add('core_text', 4, 'task is LLM-style text generation / evaluation / refinement')

    if has_any('filter', 'threshold', '>=', '<=', 'rename', 'flatten', 'derive', '字段重命名', '展平', '过滤', '新增字段'):
        add('core_text', 4, 'task needs deterministic field-level transform or rule filter')

    if has_any('emoji', 'html', 'url', 'whitespace', 'dedup', 'language detect', 'punctuation', '去重', '清洗', 'html实体', '标点', '空格'):
        add('general_text', 6, 'task mentions surface-form cleanup / language / dedup / deterministic text filters')

    if has_any('pdf', 'url to markdown', '网页', '文档摄取', 'document ingestion'):
        add('knowledge_cleaning', 20, 'task starts from documents / URLs / PDF and needs ingestion before downstream text work')
    elif has_any('markdown', 'chunk', '切块', '知识库'):
        add('knowledge_cleaning', 7, 'task may need document normalization or chunking operators')

    if has_any('instruction', 'sft', 'alpaga', 'deita', 'superfiltering'):
        add('text_sft', 7, 'task explicitly mentions SFT / instruction-quality processing')

    if has_any('reasoning', 'cot', 'math', '逻辑推理', '推理题', '数学'):
        add('reasoning', 7, 'task explicitly mentions reasoning / CoT / math')

    if has_any('code', 'program', '函数', '代码'):
        add('code', 7, 'task explicitly mentions code data')

    if has_any('conversation', 'dialog', 'chat', '多轮对话', '对话'):
        add('conversations', 6, 'task explicitly mentions conversations / multi-turn data')

    if has_any('sql', 'text2sql', '数据库'):
        add('text2sql', 7, 'task explicitly mentions SQL / database queries')

    if has_any('vqa', 'vision', '图像问答', '图片'):
        add('core_vision', 6, 'task explicitly mentions visual QA')

    if has_any('speech', 'audio', '语音'):
        add('core_speech', 6, 'task explicitly mentions speech/audio')

    if has_any('smiles', 'canonical smiles', 'smiles equivalence', '分子字符串'):
        add('chemistry', 9, 'task explicitly requests a supported SMILES operation')
    elif has_any('chemistry', '化学'):
        avoid('chemistry', 'chemistry-themed prose remains a core_text task unless SMILES work is requested')

    if any(col in {'chunk', 'text', 'doc', 'review_text', 'raw_content', 'content', 'abstract', 'paper_text', 'section_text'} for col in col_lower):
        add('core_text', 2, 'dataset columns look like text-generation inputs')

    if any(col in {'url', 'pdf_path', 'markdown', 'html'} for col in col_lower):
        add('knowledge_cleaning', 2, 'dataset columns suggest document/url ingestion')

    if any(col in {'instruction', 'response', 'answer'} for col in col_lower):
        add('text_sft', 2, 'dataset columns resemble SFT-format data')

    if any(col in {'code', 'completion'} for col in col_lower):
        add('code', 2, 'dataset columns resemble code-format data')

    if not score_map:
        add('core_text', 1, 'default starting point for scientific or general text pipelines')
        add('general_text', 1, 'secondary fallback for deterministic cleanup/filtering')

    ranked = sorted(score_map.items(), key=lambda item: (-item[1], item[0]))
    chosen = ranked[:max_categories]

    recommended = [
        {
            'category': category,
            'score': score,
            'reason': '; '.join(reason_map.get(category, [])[:2]) or 'closest available match',
        }
        for category, score in chosen
    ]

    avoid_ranked = sorted(avoid_map.items(), key=lambda item: item[0])
    avoid_items = [
        {
            'category': category,
            'score': 0,
            'reason': '; '.join(reasons[:2]),
        }
        for category, reasons in avoid_ranked
        if category not in {item['category'] for item in recommended}
    ]

    return {
        'recommended_categories': recommended,
        'avoid_categories': avoid_items[:3],
        'next_action': (
            'Call list_operators only for the recommended categories, then inspect specific candidates with '
            'get_operator_detail_by_name before create/update. Do not browse more than 2 categories unless the '
            'first pass clearly fails.'
        ),
        'query_budget': {
            'max_category_queries': max_categories,
            'why': 'Keep MCP context bounded and avoid broad catalog exploration.',
        },
    }
